### ISSUE TITLE
When analyzing behavior data alone, do we need to clean the data without extra user information from other files?

### ISSUE THREAD

**Issue by DICKJIA** [YUSIZOU11/Group-5#3]
We will use 2 original files named `CCData2018-2021`, `CustomerMedicalConditions`.

`CCData2018-2021` is about the user's behavior dataset between January 2018 and November 2021.
`CustomerMedicalConditions` is about the user health status dataset in 2021.

There is some user information in `CCData2018-2021`, and there is also some extra user information in `CustomerMedicalConditions`.
However, `CustomerMedicalConditions` only includes users who did not die in 2021, so some users in `CCData2018-2021` do not have extra information from `CustomerMedicalConditions`.

Sometimes we analyze the relationship between 2 data from different files. For example, analyzing the relationship between 'Usage' in `CCData2018-2021` and 'Gender' in `CustomerMedicalConditions`. So we need to clean the data in `CCData2018-2021` that no 'Gender' value in `CustomerMedicalConditions`.

Here is the problem, when we analyze data just from `CCData2018-2021`, do we need to clean the same data just like the previous example?

If we do not clean, the amount of sample will be different. But if we clean, the data will be incomplete.

**Comment by yangl17** [comment]
My idea is to merge the two files directly. The merged link comes from ExternalID
Note: Data with null ExternalID needs to be cleaned.

The merge code is as follows:
import csv
sns.set()


def get_data():
df1 = pd.read_csv('CCDate2018-2021.csv')
df1 = df1[df1['Role'] == 'User']

df2 = pd.read_csv('CustomerMedicalConditions04Nov21.csv')
df2 = df2[df2['Age'] >= 18]
# Filter people under 18
df2.dropna(subset=['DateOfBirth'], inplace=True)
print(df2)

column1 = df1.columns
column2 = df2.columns
print(list(column1))
print(list(column2))

df1.dropna(subset=['ExternalID'], inplace=True)
# execute "inplace" (True) on the raw data frame
df2.dropna(subset=['External ID'], inplace=True)
df2['External ID'] = df2['External ID'].astype(str)
f = open('new_data.csv', 'w', newline='', encoding='utf-8')
csv_writer = csv.writer(f)
header = list(column1) + list(column2)
csv_writer.writerow(header)
for row in df2.values:
id = row[0]
if id.replace(' ', '') ! = ' ':
id = int(id)
data = df1[df1['ExternalID'] == id]
if data.values.__len__() == 0:
# skip null values
continue

for item in data.values:
# item = np.array(item)
# print(list(item), list(row))
csv_writer.writerow(list(item) + (list(row)))

f.close()

**Comment by YUSIZOU11** [comment]
I think the point of your question is: when we analyze data just from `CCData2018-2021`, do we need to consider people these people are still alive or not?

In my opinion, the answer will vary for different analysis purposes or conditions.
Let me give some examples to show it:

## Case 1
### Hypothesis:
* How the `Overall` Activities Usage changed?
* How the `Entertainment` Activity Usage changed?
* How the `Activities related to 'Care'` Activity Usage changed? (It might increased because users might concern more about their condition during lockdown than the period prior to lockdown)

In this case, we don't need to consider any specific user, the subject of our analysis is the activity. The data to be used is how many raws there are, and the column of ['Time'], **there is no need to merge anything from any other file. Also,  it won't matter whether a user is still alive or not.**

```
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline 

CC_AllTime_data = pd.read_csv("CCDate2018-2021_AllTime_Data.csv")

# Clean data
CC_AllTime_data_user = CC_AllTime_data.loc[CC_AllTime_data['Role'] == 'User']

# Make sure there is no other roles except 'User'
for roles in CC_AllTime_data_user['Role']:
    assert roles == 'User', "There is still other roles!"

# Extract Year and Month in Time
time_data = CC_AllTime_data_user['Time']
Year_Month_data=[]
for time in time_data:
    day = time[0:6]
    if time[6] != '/':
        day += time[6]
    Year_Month_data.append(day)
    
CC_AllTime_data_users=CC_AllTime_data_user.copy()
CC_AllTime_data_users['Year_Month_data'] = time_data

# Count usage, and group by Year and month
sns.set(style='darkgrid',font_scale=0.8,palette='pastel')
plt.figure(figsize=(16,9),dpi=100)
plt.xticks(rotation=75)
plt.title("Total Usage from 2018 to 2021",fontsize=20)
plt.legend('upper right')
sns.countplot(x='Year_Month_data', data=CC_AllTime_data_users)
```

```
Entertainment_AllTime_data = CC_AllTime_data_users.loc[CC_AllTime_data['Link Title']=='Entertainment']

sns.set(style='darkgrid',font_scale=0.8,palette='pastel')
plt.figure(figsize=(16,9),dpi=100)
plt.xticks(rotation=75)
plt.title("'Entertainment' Usage from 2018 to 2021",fontsize=20)
plt.legend('upper right')
sns.countplot(x='Year_Month_data', data=Entertainment_AllTime_data)


MyCare_AllTime_data = CC_AllTime_data_users.loc[(CC_AllTime_data['Link Title']=='My Care') | (CC_AllTime_data['Link Title']=='My Care Team') | (CC_AllTime_data['Link Title']=='Care Website')]

sns.set(style='darkgrid',font_scale=0.8,palette='pastel')
plt.figure(figsize=(16,9),dpi=100)
plt.xticks(rotation=75)
plt.title("'My Care' Usage from 2018 to 2021",fontsize=20)
plt.legend('upper right')
sns.countplot(x='Year_Month_data', data=MyCare_AllTime_data)
```


## Case 2
### Hypothesis:
- Will `Activity Use Times` have correlation with users' `Care System Conditions`?
In this case, The data to be used are the column of [`Link Type`](activities) in CC_data, and the column of ['CareSysCondition'] in CMC_data, **there is need to merge two files together based on same external ID. **
So, for this kind of Hypothesis, we should highlight that because the users in CC_data are only the part of users who still alive today, we could only count the usage of this part of users, the data will be surely imcompelete if in terms of Usage, but, in terms of today's users, the data is still compelete.**

```
# For data cleaning part, the medical condition data should still be no repeat [External ID] and no null [CareSysCondtions]
# So Keep use the noCon_noID_data which has been cleaned.

#Merge data which same External ID
Time_Condition_data = pd.merge(noCon_noID_data, CC_data, on='ExternalID')
# drop group with unknown condition
Time_Condition_data_no_unknown = Time_Condition_data.loc[Time_Condition_data['CareSysCondition']!='Unknown Condition']

# To see the group with which condition contributes more in use Times
sns.set(style='darkgrid',palette='pastel')
plt.figure(figsize=(16,9),dpi=100)
plt.xticks(rotation=75)
plt.title("Activity Usage of Groups with different Care System Condition",fontsize=20)

# Use countplot and give an order by count activity use time
sns.countplot(x='CareSysCondition', data=Time_Condition_data_no_unknown, order = Time_Condition_data_no_unknown['CareSysCondition'].value_counts().index)
```
